# Generated by Django 6.0 on 2025-12-28 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('utility_type', models.CharField(choices=[('Energy', 'Energy'), ('Hot Water', 'Hot Water'), ('Heating', 'Heating'), ('Cold Water', 'Cold Water')], max_length=20)),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
