# Generated by Django 5.0.4 on 2026-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Rok')),
                ('fee_type', models.CharField(choices=[('heating', 'Energia cieplna CO'), ('hot_water', 'Energia cieplna CWU'), ('cold_water', 'Zimna woda')], max_length=20, verbose_name='Rodzaj opłaty')),
                ('quantity_included', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ilość jednostek w czynszu')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za jednostkę')),
            ],
            options={
                'ordering': ['-year', 'fee_type'],
            },
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='feerate',
            constraint=models.UniqueConstraint(fields=('year', 'fee_type'), name='unique_fee_rate_per_year'),
        ),
    ]
