# Generated by Django 6.0 on 2026-09-26 09:00

from django.conf import settings
from django.db import migrations, models


def normalize_reading_dates(apps, schema_editor):
    MeterReading = apps.get_model('expenses', 'MeterReading')
    for reading in MeterReading.objects.exclude(date__day=1):
        reading.date = reading.date.replace(day=1)
        reading.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_feerate_alter_meterreading_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerate',
            name='fee_type',
            field=models.CharField(choices=[('heating', 'Heating Energy (CO)'), ('hot_water', 'Hot Water Energy (CWU)'), ('cold_water', 'Cold Water')], max_length=20, verbose_name='Fee Type'),
        ),
        migrations.AlterField(
            model_name='feerate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feerate',
            name='quantity_included',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity included in rent'),
        ),
        migrations.AlterField(
            model_name='feerate',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='feerate',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(normalize_reading_dates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'utility_type'), name='unique_reading_per_user_month_utility', violation_error_message='A reading for this user, month and utility already exists.'),
        ),
    ]
